[env:az-delivery-devkit-v4]
platform = espressif32
board = az-delivery-devkit-v4
framework = espidf

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -std=gnu++17
    -D LOG_LOCAL_LEVEL=ESP_LOG_INFO

lib_ldf_mode = deep+

build_unflags =
    -std=gnu++11

monitor_filters =
    esp32_exception_decoder